"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['sDynaUiMain.py']
DATA_FILES = ['icon_1jpg','linkedin_icon.png','sDynaDB.db']
OPTIONS = {
    'extra_scripts':['sDynaUi.py','MDOF.py','manual.py','about.py'],
    'iconfile': 'icon.icns',
    'argv_emulation': True,
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
