from docx import Document
from docx.shared import Inches
import numpy as np
import matplotlib.pyplot as plt
from MDOF import *
import matplotlib


def prepareWord():
    # t = np.arange(0.0, 2.0, 0.01)
    # s = np.sin(2*np.pi*t)

    # plt.plot(t,s)
    # plt.title(r'$\alpha_i > \beta_i$', fontsize=20)
    # plt.text(1, -0.6, r'$\sum_{i=0}^\infty x_i$', fontsize=20)
    # plt.text(0.6, 0.6, r'$\mathcal{A}\mathrm{sin}(2 \omega t)$',
    #          fontsize=20)
    # plt.xlabel('time (s)')
    # plt.ylabel('volts (mV)')
    # plt.savefig("123.png")

    # plt.show()

    document=Document()
    header=document.add_heading("SDYNA REPORTS")
    header.alignment=1
    document.add_paragraph("")
    document.add_paragraph("This report has been automatically generated by sDyna software. ")
    # document.add_picture("123.png")
    a=4
    b=a/2
    b=int(b)
    table = document.add_table(rows=a, cols=3)
    table.allow_autofit = False
    for cell in table.columns[0].cells:
        cell.width = Inches(0.1)
    for cell in table.columns[1].cells:
        cell.width = Inches(0.1)
    for cell in table.columns[2].cells:
        cell.width = Inches(0.1)


    cell = table.cell(b, 0)
    cell.text = 'Mass(m)='
    cell=table.cell(0,1)
    cell.text='a'
    cell=table.cell(0,2)
    cell.text='a'
    cell=table.cell(1,1)
    cell.text='a'
    cell=table.cell(1,2)
    cell.text='a'



    document.save("word1.docx")

    #------------Deleting Files------------#
    #--------------------------------------#
    # import os
    # os.remove("123.png") 


    # import png
    # yapi=Yapi([100,100,100,100,100], [12800*2,30341*2,30341*2,30341*2,30341*2], 5)
    # yapi.massMatrix()
    # import scipy.io
    # scipy.io.imwrite('1234.jpg', yapi.m_matrix)